# NixOS module for the Denial Flutter-native Wayland compositor (0.4.1).
#
# Responsibilities:
#   - install the Denial package (deniald + denialctl + denial-portal +
#     denial-session + Flutter bundle + engine) and its runtime companions
#     (Xwayland, portals)
#   - optionally install the denial-update-check bin
#   - write the machine config /etc/denial/session.conf (sourced by the launcher)
#   - write the system output template /etc/denial/outputs.conf (copied to
#     $XDG_CONFIG_HOME/denial/outputs.conf on the session user's first login)
#   - install the Wayland session entry (GDM/SDDM will list "Denial")
#   - install denial-session.target for the systemd *user* manager
#   - route portals: Settings through Denial's own portal backend, general
#     portals through GTK, ScreenCast/Screenshot through the wlroots backend
#   - add the session user to video/input/render/seat groups
#
# Reference: https://github.com/denialwm/denial (docs/SESSION_STARTUP.md,
# packaging/arch/session.conf, packaging/arch/outputs.conf)
{
  config,
  lib,
  pkgs,
  # Injected by flake.nix.
  flake,
  rust-overlay,
  ...
}:

let
  cfg = config.services.denial;
  denialPkgs = import ./package.nix {
    inherit pkgs;
    denial = flake;
    inherit rust-overlay;
  };
  autoPackage =
    if cfg.useOfficialRelease then
      if cfg.uiDevelopment.enable then denialPkgs.officialReleaseWithUiDevelopment else denialPkgs.officialRelease
    else
      if cfg.uiDevelopment.enable then denialPkgs.sourceProfileWithUiDevelopment else denialPkgs.sourceProfile;
  selectedPackage = if cfg.package != null then cfg.package else autoPackage;
  pkg = selectedPackage;
  settingsPkg =
    if cfg.settings.package != null then
      cfg.settings.package
    else if cfg.settings.enable && !cfg.useOfficialRelease && cfg.package == null then
      denialPkgs.settingsApp
    else
      null;
  sessionUser = config.users.users.${cfg.user};

  sessionConf = lib.concatStringsSep "\n" (lib.flatten [
    "# Generated by NixOS. Sourced by denial-session at session start."
    "DENIAL_SHELL_PROFILE=${cfg.shellProfile}"
    "DENIAL_FLUTTER_RENDERER=${cfg.renderer}"
    "DENIAL_XWAYLAND_SCALE_MODE=${cfg.xwaylandScaleMode}"
    (lib.optional (cfg.drmDevice != null) "DENIAL_DRM_DEVICE=${cfg.drmDevice}")
    (lib.optional (cfg.renderDevice != null) "DENIAL_RENDER_DEVICE=${cfg.renderDevice}")
    (lib.mapAttrsToList (name: value: "${name}=${value}") cfg.extraSessionConf)
  ]);

  outputsConf = lib.concatStringsSep "\n" (lib.flatten [
    "# Generated by NixOS. Copied to \$XDG_CONFIG_HOME/denial/outputs.conf on first login;"
    "# Denial persists display changes to that per-user copy. Existing files are never overwritten."
    cfg.outputs
    (lib.optionalString (cfg.extraOutputsConf != "") cfg.extraOutputsConf)
  ]);
in
{
  options.services.denial = {
    enable = lib.mkEnableOption "the Denial Flutter-native Wayland compositor";

    useOfficialRelease = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Use Denial's official prebuilt release packages by default. This uses
        the upstream compositor, shell AOT bundle, Settings app, and release
        Flutter engine without Nix compiling Denial code. When disabled, the
        module uses the source/profile package path, which builds the Rust
        compositor and compiles the Dart shell profile AOT bundle from this
        flake using the prebuilt UI development toolchain.
      '';
    };

    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = null;
      description = ''
        Optional package override. When unset, the module imports
        package.nix from this flake and selects
        officialRelease/officialReleaseWithUiDevelopment or
        sourceProfile/sourceProfileWithUiDevelopment according to
        services.denial.useOfficialRelease and services.denial.uiDevelopment.enable.
      '';
    };

    selectedPackage = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      internal = true;
      description = "The resolved Denial package selected by the module.";
    };

    settings = {
      enable = lib.mkEnableOption "the standalone Denial Settings application";

      package = lib.mkOption {
        type = lib.types.nullOr lib.types.package;
        default = null;
        description = ''
          Optional Denial Settings application package. The package contains
          denial-settings and its GTK Flutter bundle, including the Displays,
          Network, Audio, Power, Keyboard, Appearance, and related pages.
        '';
      };
    };

    uiDevelopment.enable = lib.mkEnableOption ''
      Denial live Flutter UI development tools and wrappers
    '';

    # These are seed files, not declarative managed files. They are copied
    # once as ordinary writable files and are never replaced on rebuild.
    initialSettingsFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        Optional initial settings.json. It is copied to the session user's
        ~/.config/denial/settings.json only when that file does not exist.
      '';
    };

    initialShortcutsFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        Optional initial shortcuts.json. It is copied only when the user's
        file does not exist; subsequent Denial changes remain user-owned.
      '';
    };

    initialOutputsConfFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        Optional initial outputs.conf. It is copied only when the user's file
        does not exist. Use this for a complete custom output configuration.
      '';
    };

    updateCheck = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = null;
      description = ''
        Optional denial-update-check bin (built from package.nix): prints
        every field that needs updating when a new Denial release exists,
        including the freshly computed hashes.
      '';
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "denial";
      description = "Existing user that runs the Denial session; added to video/input/render/seat.";
    };

    startLocked = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Pass --start-locked to denial-session: the session starts with Denial's
        native PAM-backed lock screen before the shell renders. Use for
        autologin/direct-start setups; regular display-manager logins already
        authenticated the user and should keep this disabled.
      '';
    };

    renderer = lib.mkOption {
      type = lib.types.enum [ "impeller" "skia" ];
      default = "impeller";
      description = "Flutter renderer: impeller (compositor-integrated GLES, default) or skia (retained compatibility path).";
    };

    xwaylandScaleMode = lib.mkOption {
      type = lib.types.enum [ "fractional" "integer" ];
      default = "fractional";
      description = "Xwayland scaling: fractional (exact output density) or integer (legacy X11 DPI compatibility).";
    };

    shellProfile = lib.mkOption {
      type = lib.types.enum [ "desktop" "mobile" ];
      default = "desktop";
      description = "Denial shell profile.";
    };

    drmDevice = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Override the KMS DRM device, e.g. /dev/dri/card0. Unset = automatic boot-GPU selection.";
    };

    renderDevice = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Separate GBM/EGL render node, e.g. /dev/dri/renderD128, for split-GPU machines. Unset = same as drmDevice.";
    };

    outputs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = ''
        Lines for /etc/denial/outputs.conf (system template; the launcher copies
        it to the session user's ~/.config/denial/outputs.conf on first login).
        Format: "CONNECTOR=X,Y", "mode=CONNECTOR,W,H,MILLIHZ",
        "scale=CONNECTOR,F", "primary=CONNECTOR", "transform=CONNECTOR,90",
        "vrr=CONNECTOR", "system_bar=SIDE,THICKNESS[,OUTPUT]",
        "maximize_padding=N". Empty = auto-discover outputs.
      '';
    };

    extraOutputsConf = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra raw lines appended to /etc/denial/outputs.conf.";
    };

    extraSessionConf = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = { DENIAL_RUST_LOG = "deniald=debug"; };
      description = "Extra KEY=VALUE entries appended to /etc/denial/session.conf.";
    };

    enableXwayland = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Add Xwayland to systemPackages (required by the denial-session launcher).";
    };

    enablePortals = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Install Denial's portal backend (Settings keys) and xdg-desktop-portal
        backends, and route portals: GTK by default, Denial's own backend for
        Settings, and xdg-desktop-portal-wlr for ScreenCast/Screenshot.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = config.users.users ? ${cfg.user};
        message = "services.denial.user is set to '${cfg.user}', but no such user exists. Set services.denial.user to an existing user.";
      }
    ];

    services.denial.selectedPackage = selectedPackage;

    environment.systemPackages = [ pkg ]
      ++ lib.optional (cfg.settings.enable && settingsPkg != null)
        settingsPkg
      ++ lib.optional (cfg.updateCheck != null) cfg.updateCheck
      ++ lib.optionals cfg.enableXwayland [ pkgs.xwayland pkgs.zenity ]
      ++ lib.optionals cfg.enablePortals [
        pkgs.xdg-desktop-portal
        pkgs.xdg-desktop-portal-gtk
        pkgs.xdg-desktop-portal-wlr
      ];

    # Denial runs a raw-embedder compositor on DRM/KMS: the session user needs
    # access to the GPU + input nodes. Groups are defined explicitly so the
    # configuration does not depend on another module having created them.
    users.groups.video = { };
    users.groups.input = { };
    users.groups.render = { };
    users.groups.seat = { };
    users.users.${cfg.user}.extraGroups = lib.mkIf (config.users.users ? ${cfg.user}) [
      "video"
      "input"
      "render"
      "seat"
    ];

    environment.etc."denial/session.conf".text = sessionConf + "\n";
    environment.etc."denial/outputs.conf".text = outputsConf + "\n";

    # Denial's wlr portal backend consumes a zenity-based screen-share chooser
    # (see the package's /etc/xdg/xdg-desktop-portal-wlr/Denial).
    environment.etc."xdg-desktop-portal-wlr/Denial".source =
      lib.mkIf cfg.enablePortals "${pkg}/etc/xdg/xdg-desktop-portal-wlr/Denial";

    environment.variables = lib.mkIf cfg.uiDevelopment.enable {
      # Settings app uses these overrides instead of assuming a mutable
      # /usr/bin installation. The selected package must be the
      # withUiDevelopment variant when this is enabled.
      DENIAL_CONTROL_TOOL = "${pkg}/bin/denialctl";
      DENIAL_DEVELOPMENT_TOOL = "${pkg}/bin/denial-ui";
    };

    system.activationScripts.denial-initial-config = lib.mkIf (
      cfg.initialSettingsFile != null
      || cfg.initialShortcutsFile != null
      || cfg.initialOutputsConfFile != null
    ) (lib.stringAfter [ "users" ] ''
      set -eu
      copy_denial_seed() {
        source="$1"
        target="$2"
        if [ -e "$target" ] || [ -L "$target" ]; then
          return 0
        fi
        if [ ! -f "$source" ]; then
          echo "denial: initial configuration is not a regular file: $source" >&2
          return 1
        fi
        parent="$(dirname -- "$target")"
        install -d -m 700 -o ${cfg.user} -g ${sessionUser.group} "$parent"
        temporary="$(mktemp "$parent/.denial-initial.XXXXXX")"
        cp -- "$source" "$temporary"
        chown ${cfg.user}:${sessionUser.group} "$temporary"
        chmod 600 "$temporary"
        mv -- "$temporary" "$target"
      }

      ${lib.optionalString (cfg.initialSettingsFile != null) ''
        copy_denial_seed "${cfg.initialSettingsFile}" "${sessionUser.home}/.config/denial/settings.json"
      ''}
      ${lib.optionalString (cfg.initialShortcutsFile != null) ''
        copy_denial_seed "${cfg.initialShortcutsFile}" "${sessionUser.home}/.config/denial/shortcuts.json"
      ''}
      ${lib.optionalString (cfg.initialOutputsConfFile != null) ''
        copy_denial_seed "${cfg.initialOutputsConfFile}" "${sessionUser.home}/.config/denial/outputs.conf"
      ''}
    '');

    environment.etc."wayland-sessions/denial.desktop".text = ''
      [Desktop Entry]
      Name=Denial
      Comment=Flutter-native Wayland compositor and desktop shell
      Exec=${pkg}/bin/denial-session${lib.optionalString cfg.startLocked " --start-locked"}
      TryExec=${pkg}/bin/denial-session
      Type=Application
      DesktopNames=Denial
      Keywords=wayland;compositor;flutter;rust;
    '';

    # `/etc/systemd/user` is itself generated as one directory entry by the
    # NixOS systemd module. Define these targets through systemd.user instead
    # of trying to place a file beneath that symlinked directory.
    systemd.user.targets.denial-session = {
      description = "Denial graphical session";
      documentation = [ "https://github.com/denialwm/denial" ];
      bindsTo = [ "graphical-session.target" ];
      wants = [ "xdg-desktop-autostart.target" ];
      before = [ "graphical-session.target" "xdg-desktop-autostart.target" ];
    };

    systemd.user.services.denial-portal = lib.mkIf cfg.enablePortals {
      description = "Denial desktop portal backend";
      documentation = [ "https://github.com/denialwm/denial" ];
      partOf = [ "denial-session.target" ];
      after = [ "denial-session.target" ];
      serviceConfig = {
        Type = "dbus";
        BusName = "org.freedesktop.impl.portal.desktop.denial";
        ExecStart = "${pkg}/bin/denial-portal";
        Restart = "on-failure";
        RestartSec = "250ms";
      };
    };

    xdg.portal.enable = lib.mkDefault true;
    xdg.portal.extraPortals = lib.mkIf cfg.enablePortals [ pkg ];
    xdg.portal.config.denial = lib.mkIf cfg.enablePortals {
      "default" = "gtk";
      "org.freedesktop.impl.portal.Settings" = "denial;gtk";
      "org.freedesktop.impl.portal.ScreenCast" = "wlr";
      "org.freedesktop.impl.portal.Screenshot" = "wlr";
    };
  };
}
